"""empty message

Revision ID: 21418c320ba2
Revises: 7d5acdda0d94
Create Date: 2025-08-13 09:59:42.405630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21418c320ba2'
down_revision = '7d5acdda0d94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###
