"""empty message

Revision ID: 4940c418a023
Revises: 1e43c3ec69f0
Create Date: 2025-08-20 09:41:18.284871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4940c418a023'
down_revision = '1e43c3ec69f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.String(length=100), nullable=False))
        batch_op.create_foreign_key(None, 'item', ['id'], ['id'])
        batch_op.drop_column('uid')

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.String(length=100), nullable=False))
        batch_op.create_foreign_key(None, 'item', ['id'], ['id'])
        batch_op.drop_column('uid')

    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.String(length=100), nullable=False))
        batch_op.create_foreign_key(None, 'item', ['id'], ['id'])
        batch_op.drop_column('uid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uid', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id')

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uid', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id')

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uid', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
