"""empty message

Revision ID: 7d5acdda0d94
Revises: ea2135ae2e1c
Create Date: 2025-07-23 23:23:43.136414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d5acdda0d94'
down_revision = 'ea2135ae2e1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_uid', sa.String(length=100), nullable=False))
        batch_op.create_foreign_key(None, 'item', ['item_uid'], ['uid'])
        batch_op.drop_column('favorite_uid')
        batch_op.drop_column('id')

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_favorite', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('is_favorite')

    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('favorite_uid', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('item_uid')

    # ### end Alembic commands ###
